### PR TITLE
link to files

### PR DESCRIPTION
**Pull request by taivu**
link to files, works for files nested in folders too.

### CODE REVIEW

**Comment by OleVik** [comment]
What in particular does this achieve?

**Comment by taivu** [comment]
$value returns a server side path (var/www). When clicking on file, responds with 404.

This takes the path and cuts out server stuff and allows files to be accessed by clicking (returns the file)

- Tai

**Comment by taivu** [comment]
Also $parts['basename'] returns file name with extension.

- Tai

**Comment by OleVik** [comment]
I see, I'll look into it as an issue and find a solution.

**Comment by taivu** [comment]
Ok. Ive tested this with a folder with multiple nested folders and files and its works for me. Thanks for creating this plugin, fit the bill for what I needed.

- Tai

**Comment by OleVik** [comment]
Your solution, whilst simple and elegant, caused some issues with cross-testing in varied PHP-installations, so I drafted a (hopefully) somewhat more robust solution. Thank you for the contributions though, they are much appreciated as plugins can always improve and I do not always have time to test changes on live-installations of Grav.

Closed with [v1.0.6](https://github.com/OleVik/grav-plugin-directorylisting/releases/tag/v1.0.6).

**Pull request closed without merging**
